### ISSUE TITLE
`DefaultRenderingStrategy` throwing circular dependency exception on route render failure.

### ISSUE THREAD

**Issue by Wilt** [zfcampus/zf-hal#101]
When we request a collection and we set an invalid (non existing) route for the child resources in our `metadata_map` the rendering fails and returns a `ZF\Hal\Exception\CircularReferenceException`.
It is hard to debug since the real cause of the issue lies in the [`fromLink` method  on line 698](https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L698) where the rendering of the url from the `$linkDefinition` config fails. 

The problem lies in [DefaultRenderingStrategy](https://github.com/zendframework/zend-mvc/blob/master/src/View/Http/DefaultRenderingStrategy.php#L105) at line 105 where it only catches errors in events of type `MvcEvent::EVENT_RENDER_ERROR`. 

On failure `Url` helper returns an exception of type `Zend\Mvc\Router\Exception\RuntimeException` but this exception is not caught since `$e->getName()` equals `MvcEvent::EVENT_RENDER` ('render') and not `MvcEvent::EVENT_RENDER_ERROR` ('render.error').

After failure the `Hal` plugin tries to render the same `Collection` resource again and then the `CircularReferenceException` occurs. Somehow the `MvcEvent::EVENT_RENDER_ERROR` triggered [on line 113](https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/View/Http/DefaultRenderingStrategy.php#L113) never results in output.

I don't know how to properly solve this. Maybe a discussion here could help me understand on how to deal with this issue...

**Comment by weierophinney** [comment]
@Wilt The line in the `DefaultRendereringStrategy` you reference is not doing what you think it is.

Essentially, the `DefaultRendereringStrategy` is listening on *both* the `EVENT_RENDER` *and* `EVENT_RENDER_ERROR` events. The line you reference is inside a `catch`, and it's ensuring that we don't get into a recursive situation whereby an exception thrown while rendering an error template leads to re-triggering of the `EVENT_RENDER_ERROR` event! (We're actually catching *any* exception; that line is checking to see which *event* led to execution of the method in the first place.)

In doing some investigation, however, I think I understand what's happening. zf-api-problem's `ApiProblemListener` is setup to register the module's `RenderErrorListener` *if* the matched controller is in a list of `render_error_controllers`. Unfortunately, we're not populating that when we create controllers via the admin!

I'll work on a solution to that shortly! Thanks for the report!

**Comment by weierophinney** [comment]
@Wilt Per my comment on zfcampus/zf-api-problem#34, I've determined that we conditionally register zf-api-problem's `RenderErrorListener` inside of `ZF\Apigility\Module` when a `JsonModel` or `HalJsonModel` is detected by a listener on `EVENT_RENDER`; this should ensure you get a problem detail. Since you're not, I need a reproduce case, as I'm now just stabbing in the dark; I have no idea how to trigger the behavior you've observed.

**Comment by Wilt** [comment]
'metadata_map' => array(

**Comment by Wilt** [comment]
It happens when I create metadata with a `links` key and inside this links I add a link with a route that does not exist. So for example this: 

        'metadata_map' => array(
            User\Entity\User => array(
                'route_name'             => 'api/v1/users',
                'is_collection'          => false,
                'route_identifier_name' => 'user_id',
                'entity_identifier_name' => 'id',
                'links' => array(
                    'contacts' => array(
                        'rel' => 'contacts',
                        'route' => array(
                            'name' => 'api/v1/contacts',
                        )
                    )
                )
            )
        )

Where route contacts doesn't exist in the route config.
If you don't get the error with this then it could be somewhere in my custom added code.

**Comment by Wilt** [comment]
I made [a pull request](https://github.com/zfcampus/zf-hal/pull/131) with a test for showing what and where the exception is thrown (`Zend\Mvc\Router\Exception\RuntimeException`).

This never results in a `ApiProblem` response.

**Comment by Wilt** [comment]
@weierophinney did you ever look at this test in the PR I made?

**Comment by Wilt** [comment]
Thanks!
