### ISSUE TITLE
500 if page param is lower than 1

### ISSUE THREAD

**Issue by snapshotpl** [zfcampus/zf-hal#129]
I get 500 status code when in request page param is lower than 1. For example: `/resource?page=0`

I think that's client problem so status code should be 400. What are you think?

https://github.com/zfcampus/zf-hal/blob/master/src/Collection.php#L282

**Comment by TomHAnderson** [comment]
:+1:

**Comment by bhaku** [comment]
+1

**Comment by dnahrebecki** [comment]
:+1:

**Comment by andrevus** [comment]
:+1:

**Comment by vegat** [comment]
:+1:

**Comment by snapshotpl** [comment]
I have find out that this issue is fixed in master. However I page_size param had same issue so I fix it. https://github.com/zfcampus/zf-rest/pull/94

**Comment by snapshotpl** [comment]
Here is fix https://github.com/zfcampus/zf-rest/blob/master/src/RestController.php#L953

**Comment by Wilt** [comment]
Page size should be allowed to be -1 (dectivate paginator).
Please take this into account in your solution.
