### ISSUE TITLE
Curies

### ISSUE THREAD

**Issue by gsomoza** [zfcampus/zf-hal#137]
I've been looking around and there doesn't seem to be much support for "curies" in this project.

At first I thought it would be OK to just create a new Link with rel "curies" and then the rest of the info, but it turns out that the reserved "curies" rel is meant to be an array / collection of elements instead of a single link.

Have I missed a way to specify curies? And if not: would you be interested (short-term) in a PR?

**Comment by gabrielsomoza** [comment]
Ok, I just realized: you can add multiple links to the same "rel" and it will automatically create a collection.

The thing is that the "curies" rel is always meant to be a "set of links", based on the [formal specification|https://tools.ietf.org/html/draft-kelly-json-hal-07#section-8.2].

**Comment by gsomoza** [comment]
Closing in favor of https://github.com/zfcampus/zf-hal/pull/163
