### ISSUE TITLE
Handling embedded entity collections

### ISSUE THREAD

**Issue by npetrovski** [zfcampus/zf-hal#23]
Recently I was playing with the lib and I faced a problem when an entity has an embedded collection. To be more specific I did play with Apigility and Doctrine, and the problem came when I received an entity with ManyToMany relation. I did a quick fix https://github.com/npetrovski/zf-hal/commit/d58145cb372e0c62dbcbcd3e9e448c07f7aa0a40 but I wondering if I miss something?

**Comment by rrisse** [comment]
Hi I have the same issue using Apigility and Doctrine but I did not understand your fix. Could please help me.

**Comment by rrisse** [comment]
Hi 
by modifying the Metadata_map I get 
 Maximum function nesting level of '100' reached, aborting!

**Comment by PowerKiKi** [comment]
@rrisse an alternative solution is to add hydrator strategy as described there: https://github.com/zfcampus/zf-apigility-doctrine/issues/205#issuecomment-121817568

I believe in both case you will have to add ``maxdepth`` key in ``zf-hall`` config, something like:

```php
'zf-hal' => array(
    'metadata_map' => array(
        'Application\\Model\\User' => array(
            'maxdepth' => 2,
            // more things...
        ),
    ),
),
```
