### ISSUE TITLE
$entity created using Metadata is converted to array (extracted) twice. Why is this?

### ISSUE THREAD

**Issue by Wilt** [zfcampus/zf-hal#64]
If in the `createEntity` method the `$entity` is available in the `MetadataMap` it will be changed into a hal `Entity` in the first case of the switch using the `createEntityFromMetadata` method:

https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L765

During this process the data is extracted from the entity by using the `convertEntityToArray` method:

https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L708

The result is stored in a `$generatedEntity` variable. Instead of using this generated entity directly another instance of hal `Entity` is created like this:
```
$halEntity = new Entity($entity, $generatedEntity->id);
```
Since in the first param `$entity` is an object the `convertEntityToArray` will be called once more when later rendering the entity in the `renderEntity` method. So we will be hydrating the same entity twice:

https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L500

Why is this? Why not stick with the $generatedEntity that holds the array?

**Comment by weierophinney** [comment]
The reason is so that when later events are triggered, developers have access to the original, raw entity in case they wish to do introspection or manipulation of it prior to rendering.
