### ISSUE TITLE
Self Links are Forced

### ISSUE THREAD

**Issue by gabrielsomoza** [zfcampus/zf-hal#80]
"Self" links are forced in `\ZF\Hal\Plugin\Hal::createEntityFromMetadata()`, around line 764 (toward the end of the function):

```php
$entity   = new Entity($data, $id);
$links    = $entity->getLinks();
$this->marshalMetadataLinks($metadata, $links);
if (!$links->has('self')) {
    $link = $this->marshalSelfLinkFromMetadata($metadata, $object, $id, $metadata->getRouteIdentifierName());
    $links->add($link);
}
```

What's interesting is that links for collections are indeed not required in method `createCollectionFromMetadata()`, around line 867:

```php
if (!$links->has('self')
        // this extra condition avoids the "self" link unless a url or route are specified
        && ($metadata->hasUrl() || $metadata->hasRoute())
    ) {
    $link = $this->marshalSelfLinkFromMetadata($metadata, $object);
    $links->add($link);
}
```

In the HAL specification "self" links are not "required". I have a use-case with Apigility where I want to have the HAL mapping configured for an entity (so that it gets extracted) but while providing NO "self" links (simply because there's no REST service for that entity).

Would it be ok if we make the condition in `createEntityFromMetadata()` similar to the condition in `createCollectionFromMetadata()`?

**Comment by weierophinney** [comment]
@gabrielsomoza Send me a PR, then. :)

**Comment by gabrielsomoza** [comment]
Took me a while to get to this, but there you go :)
