### ISSUE TITLE
circular dependancy exception

### ISSUE THREAD

**Issue by matwright** [zfcampus/zf-hal#82]
https://github.com/zfcampus/zf-hal/commit/98209f2025e0b6d933b61d920e83b1f00469e1b6

This commit has created a circular dependancy, the viewHelperFactory depends on the controllerPluginFactory and vice-versa.

Resulting in a Zend\ServiceManager\Exception\CircularDependencyFoundException :

*Circular dependency for LazyServiceLoader was found for instance Hal*

Shouldn't the Plugin/Hal.php object itself be managed via the ServiceManager and returned from the view and controller plugin factories ?

**Comment by jaapio** [comment]
this one dupplicates #81

**Comment by matwright** [comment]
I'll close and repost my comment to the previous ticket
