### ISSUE TITLE
Plugin\Hal::convertEntityToArray exposes private and protected properties

### ISSUE THREAD

**Issue by steverhoades** [zfcampus/zf-hal#91]
https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L1284

The function exposes private and protected properties of an object.  This should really use get_object_vars instead which will properly only grab the publicly declared properties of a class.

**Comment by weierophinney** [comment]
@steverhoades Did you ever submit the above patch as a PR?

**Comment by steverhoades** [comment]
@weierophinney yes, this has been merged.
