### ISSUE TITLE
Differentiate embedded entities and not ones when rendering

### ISSUE THREAD

**Issue by jbenoit2011** [zfcampus/zf-hal#95]
Currently, the entity rendering makes no difference if it is embedded or not.
Could it be possible to allow to treat embedded entities differently ?

E.g: I have an entity `User`, and I want filter this one differently when it is embedded (to remove more properties and make it lighter).

The filtering is the responsibility of the hydrator, but it does not know when the entity is embedded. Whereas the `Hal` plugin knows it. So I think it should be passed from the `Hal` plugin to the hydrator. But I fear it leads to bad design. So maybe there is another way ?

5 minutes later:

A better design, could be to allow to provide a factory to the `hydrator` key under `metadata_map`. In this factory, the context would be injected, it would allow to create a custom hydrator.

**Comment by weierophinney** [comment]
@jbenoit2011 For the sake of simplicity, we did not provide this feature. As you note, the plugin does not know if the entity is embedded or not during rendering. We could potentially add another flag that is toggled when an entity is being rendered as an embedded one, but that raises new questions: maybe you want to show the whole entity when in a collection, but not when embedded singly, or vice versa.

If you want full control over rendering, you can hand-craft your response payloads. Create a `ZF\Hal\Entity` and/or `ZF\Hal\Collection` instance by hand, and compose in the various items you want, serializing them however you want as you do so. This is already supported, and is how we recommend customizing your response payloads.
